version: '3'

services:
  db:
    image: postgres
    container_name: vk-groups-postgres
    env_file:
      - config/db.env
    ports:
      - "0.0.0.0:15432:5432"
  groups-loader:
    build: .
    image: go-vk-groups-loader
    container_name: vk-groups-loader
    depends_on:
      - db
