#!/bin/bash

read -r -p "VK Token: " VK_TOKEN
if [ "${VK_TOKEN}" == "" ]
then
  echo "Error: VK Token must be specify"
  exit 1
fi

read -r -p "PostgreSQL user (default: postgres): " PG_USER
if [ "${PG_USER}" == "" ]
then
  PG_USER=postgres
fi

read -r -p "PostgreSQL password: " PG_PASS
if [ "${PG_PASS}" == "" ]
then
  echo "Error: PostgreSQL password must be specify"
  exit 1
fi

read -r -p "PostgreSQL db name (default: vkgroups): " PG_NAME
if [ "${PG_NAME}" == "" ]
then
  PG_NAME=vkgroups
fi

export PG_HOST=db
export PH_PORT=5432
export PG_USER="${PG_USER}"
export PG_PASS="${PG_PASS}"
export PG_NAME="${PG_NAME}"

cat > config/config.json <<- EOM
{
  "pguser":   "${PG_USER}",
  "pgpass":   "${PG_PASS}",
  "pgname":   "${PG_NAME}",
  "pghost":   "${PG_HOST}",
  "pgport":   "${PG_PORT}",
  "vktoken":  "${VK_TOKEN}",
  "interval": 600
}
EOM

sudo docker-compose build -e PG_NAME="${PG_NAME}" -e PG_USER="${PG_USER}" -e PG_PASS="${PG_PASS}"
